# Generated by Django 2.1.7 on 2019-03-18 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cover', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=12)),
                ('residence', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Relation'),
        ),
    ]
