# Generated by Django 2.1.7 on 2019-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='relation',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
